// This file is automatically generated by Gemini.

'use server';

/**
 * @fileOverview A Genkit flow for generating weekly summary messages for students with missing or incomplete homework.
 *
 * - generateWeeklySummary - A function that generates weekly summary messages for students.
 * - GenerateWeeklySummaryInput - The input type for the generateWeeklySummary function.
 * - GenerateWeeklySummaryOutput - The return type for the generateWeeklySummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateWeeklySummaryInputSchema = z.object({
  studentName: z.string().describe('The name of the student.'),
  week: z.string().describe('The week for which to generate the summary.'),
  missingAssignments: z
    .array(z.string())
    .describe('A list of missing assignments.'),
  incompleteAssignments: z
    .array(z.string())
    .describe('A list of incomplete assignments.'),
  correctedAssignments: z
    .array(z.string())
    .describe(
      'A list of assignments that were initially missing/incomplete but have since been corrected during the week.'
    ),
  forgottenBooks: z
    .array(z.string())
    .describe('A list of subjects for which the student forgot the book.'),
});

export type GenerateWeeklySummaryInput = z.infer<
  typeof GenerateWeeklySummaryInputSchema
>;

const GenerateWeeklySummaryOutputSchema = z.object({
  message: z.string().describe('The generated summary message for the student.'),
});

export type GenerateWeeklySummaryOutput = z.infer<
  typeof GenerateWeeklySummaryOutputSchema
>;

export async function generateWeeklySummary(
  input: GenerateWeeklySummaryInput
): Promise<GenerateWeeklySummaryOutput> {
  return generateWeeklySummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateWeeklySummaryPrompt',
  input: {schema: GenerateWeeklySummaryInputSchema},
  output: {schema: GenerateWeeklySummaryOutputSchema},
  prompt: `You are a helpful teacher generating summary messages for students and their parents.

  Compose a message for {{studentName}} for week {{week}}.

  The message should include:
  - A list of missing assignments: {{missingAssignments}}
  - A list of incomplete assignments: {{incompleteAssignments}}
  - A list of assignments that have been corrected during the week: {{correctedAssignments}}
  - A list of subjects for which the student forgot the book: {{forgottenBooks}}

  "Syk/Fravær" should be considered valid absences and not included in the message. Acknowledge any assignments that were corrected during the week.
  The tone should be encouraging and supportive.`,
});

const generateWeeklySummaryFlow = ai.defineFlow(
  {
    name: 'generateWeeklySummaryFlow',
    inputSchema: GenerateWeeklySummaryInputSchema,
    outputSchema: GenerateWeeklySummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
