// This file is automatically generated by Gemini.

'use server';

/**
 * @fileOverview A Genkit flow for generating weekly summary messages for parents about students with missing homework or iPad issues.
 *
 * - generateWeeklySummary - A function that generates weekly summary messages.
 * - GenerateWeeklySummaryInput - The input type for the generateWeeklySummary function.
 * - GenerateWeeklySummaryOutput - The return type for the generateWeeklySummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateWeeklySummaryInputSchema = z.object({
  studentName: z.string().describe('The name of the student.'),
  week: z.string().describe('The week for which to generate the summary (e.g., "Uke 34").'),
  missingAssignments: z
    .array(z.string())
    .describe('A list of missing assignments.'),
  incompleteAssignments: z
    .array(z.string())
    .describe('A list of assignments that need corrections.'),
  forgottenBooks: z
    .array(z.string())
    .describe('A list of subjects for which the student forgot the book.'),
  ipadNotChargedCount: z.number().describe('Number of times the iPad was not charged.'),
  ipadNotBroughtCount: z.number().describe('Number of times the iPad was not brought to school.'),
});

export type GenerateWeeklySummaryInput = z.infer<
  typeof GenerateWeeklySummaryInputSchema
>;

const GenerateWeeklySummaryOutputSchema = z.object({
  message: z.string().describe('The generated summary message for the parents.'),
});

export type GenerateWeeklySummaryOutput = z.infer<
  typeof GenerateWeeklySummaryOutputSchema
>;

export async function generateWeeklySummary(
  input: GenerateWeeklySummaryInput
): Promise<GenerateWeeklySummaryOutput> {
  return generateWeeklySummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateWeeklySummaryPrompt',
  input: {schema: GenerateWeeklySummaryInputSchema},
  output: {schema: GenerateWeeklySummaryOutputSchema},
  prompt: `You are a helpful teacher in a Norwegian school, writing a weekly summary message to the parents of a student. The tone should be professional, informative, and neutral.

  The message is for the parents of **{{studentName}}** regarding **{{week}}**.

  Include the following points ONLY if they have occurred. If a list is empty or a count is zero, do not mention that category in the message.

  - **Ikke levert (Missing assignments):** {{#if missingAssignments}}
    - {{#each missingAssignments}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
    {{/if}}
  - **Må rettes (Needs correction):** {{#if incompleteAssignments}}
    - {{#each incompleteAssignments}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
    {{/if}}
  - **Glemt bok (Forgotten book):** {{#if forgottenBooks}}
    - {{#each forgottenBooks}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
    {{/if}}
  - **iPad ikke ladet (iPad not charged):** {{#if ipadNotChargedCount}}{{ipadNotChargedCount}} gang(er){{/if}}
  - **iPad ikke medbrakt (iPad not brought):** {{#if ipadNotBroughtCount}}{{ipadNotBroughtCount}} gang(er){{/if}}

  Start the message with a polite opening. Combine the points into a concise and clear message. End with a polite closing.

  Example message for a student with issues:
  "Hei,
  En liten oppsummering for [Student Name] i [Uke].
  
  Mangler/må rettes:
  - Norsk: Leselekse
  
  iPad:
  - Ikke ladet: 1 gang
  
  Vennlig hilsen,
  Læreren"
  `,
});

const generateWeeklySummaryFlow = ai.defineFlow(
  {
    name: 'generateWeeklySummaryFlow',
    inputSchema: GenerateWeeklySummaryInputSchema,
    outputSchema: GenerateWeeklySummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
